#!/usr/bin/env bash

## Version:\033[0;35m 2.7.4 \033[0m
## Wrapper for anime-downloader. Allows using watchlist given by trackma for a better anime watching cli experience.
## Homepage:\033[0;34m https://github.com/RaitaroH/adl \033[0m
## Usage:\033[0;36m $adl [Option...] [Argument...] \033[0m
## \033[1;33mOptions:\033[0m
##   -p, --player      Define player used for streaming. Ex: \033[0;36m$adl -p mpv\033[0m;
##   -i, --provider    Define provider used for streaming (check \033[0;36m$anime dl --help\033[0m for providers list);
##   -s, --show        Watch custom show. Ep nr optional, careful with the quotes. Ex: \033[0;36m$adl -s "gegege 2018"\033[0m;
##   -n, --number      Specify episode number that will be used with '-s / --show' option. Ex: \033[0;36m$adl -s "gegege 2018" -n "4"\033[0m;
##   -y, --no-confirm  Assume default option for all promts, except watch another anime. Requires anime-downloader git/master;
##   -r, --retrieve    Run trackma retrieve to update local list;
##   -d, --download    Download instead of streaming;
##   -l, --local       Use local files instead of streaming. Define folder to be used for local as argument;
##   -f, --frece       Optionally adl can use frece to show most watched anime at the top of the list in fzf;
##   -a, --account     By default trackma will use account 1. Use \033[0;36m$adl -a "2"\033[0m for example to change trackma account;
##   -q, --query       By default trackma will list watching. Use \033[0;36m$adl -q "query"\033[0m to change the list.
##                     Available queries: watching, completed, rewatching, paused, dropped, plantowatch.
##   -u, --update      Update this script from github master;
##   -c, --cover       Show cover/artwork image during anime selction, using ueberzug;
##   -h, --help        Display help and exit;
##   -v, --version     Display version and exit.

DB_FILE="/home/$USER/.local/share/adl.db"
ENTRIES_FILE="/tmp/adl.txt"
FZF_FILE="/tmp/adl.fzf"
yes=""
show_title=""
show_episode=""
player="mpv"
provider=""
account="1"
query="watching"
retrieve=""
download="0"
ctrlc="0"
watched="0"
windows_specific_cmd="ipconfig" # you can change it to any windows specific command
# For local anime viewing define directory and change local to 1
local="0"
animedir=""
# change digit to show that many previous episodes during multi fzf select
mbuffer="0"
# To use covers with fzf by default
# covers="1"
# Function to reset some vars
reset_vars() { #{{{
  ctrlc="0" #making sure this counter is reset
  # err="0"
  ferr="0"
  show_title=""
  show_episode=""
  provider_ans=""
} #}}}

# An array of anime that end with a fullstop/period/dot
# required for trackma updating
declare -a exceptions=("Bakuman" "Araburu Kisetsu no Otome-domo yo" "Doukyonin wa Hiza" "Tokidoki" "Atama no Ue" "Kobato" "Beelzebub-jou no Okinimesu mama" "Dragon, Ie wo Kau" "Hige wo Soru. Soshite Joshikousei wo Hirou" "Komi-san wa, Komyushou desu")
check_exceptions() {
  # test if an anime title has a period at the end or not. If yes add one
  for t in "${exceptions[@]}"; do [ "$title" == "$t" ] && title="${title}."; done
}

check_player() { #{{{
  # Check platform and Exit if "$player" is not installed
  if ! [ -x "$(command -v $windows_specific_cmd)" ]; then
    echo "Platform:Linux"
    if ! [ -x "$(command -v $player)" ]; then
      echo "Error: '$player' is not installed." >&2
      print_options
      exit 1
    fi
  else
    echo "Platform:Windows"
    start player_check.bat "$player"
    sleep 0.4s
    player_bool="$(cat player_bool_file)"
    rm -rf player_bool_file
    if [ "$player_bool" -eq 0 ]; then
      echo "Error: '$player' is not installed." >&2
      print_options
      exit 1
    fi
  fi
  clear
} #}}}
check_frece() { #{{{
  if ! [ -x "$(command -v frece)" ]; then
    echo "Error: 'frece' is not installed." >&2
    print_options
    exit 1
  fi
  clear
} #}}}
check_covers() { #{{{
  if ! [ -x "$(command -v ueberzug)" ]; then
    echo "Error: Cannot display covers due to missing package 'ueberzug'." >&2
    print_options
    exit 1
  fi
  clear
} #}}}
trap_ctrlc()      { ctrlc=1 ;}
color_print()     { echo -e "\033[0;36m$* \033[0m" ;} #for normal output
color_prompt()    { echo -en "\033[0;34m$*\033[0m" ;} #for user input
print_help()      { echo -e "$(sed -n "s/##\ //p" "$0")" ;} # more compact than { grep "^##" "$0" | sed -e "s/^...//" ;}
print_queries()   { print_help | grep 'queries' | sed -e 's/^[ \t]*//' ;}
print_options()   { print_help | tail +5 ;}
print_version()   { print_help | head -2 ;}
print_noselect()  { color_print "Nothing was selected. Exiting..." ;}
print_noconfirm() { color_print "\nDefault option chosen due to option '-y'.\n" ;}
watching_prompt() {
  [[ "$download" == "0" ]] && var="watching" || var="downloading"
  echo -e "\nNow $var \033[0;34m$1\033[0m, $2 \033[0;34m$3 \033[0m"
}
get_list()        { #{{{
  if [[ "$retrieve" == "1" ]]; then
    color_print "Running trackma retrieve for account $account..."
    trackma -a "$account" retrieve
    clear
  fi
  # change list
  case "$query" in
    "completed"|"rewatching"|"paused"|"dropped"|"plantowatch")
      # 'trackma -a "$account" -' is needed to prevent: "BrokenPipeError: [Errno 32] Broken pipe"
      # see https://github.com/z411/trackma/issues/79
      # LINES and COLUMNS vars for long titles
      # see https://github.com/z411/trackma/commit/020c0a25637f7368e6c075bcbe67cd938a51b818
      tlist=$(echo -e "filter $query\nlist\nexit" | LINES=25 COLUMNS=130 trackma -a "$account" - | \
              sed -n '/[[:space:]].1/,${p;/results/q}' | head -n -1)
    ;;
    "watching")
      # the above works with query=watching, but that method is hacky
      # using official way for best compatability
      tlist=$(LINES=25 COLUMNS=130 trackma -a "$account" list | head -n -2 | tail -n +2)
    ;;
  esac
  if [[ "$tlist" == "" ]]; then
    color_print "trackma returned empty '$query' list. Choose another list query."
    print_queries
    exit 1
  fi
} #}}}
process_list()    {
  perl -pe 's/\x1b\[[0-9;]*m//g ; s/^.+?[^\s]\s+(.+?(?=\.\.))\.+\ +(\d+).[^\d]\ (\d+|\?)\s+(\d*[.]?\d+).+$/\1|\2|\3|\4|/g'
}
# {{{
# Entry manipulation explination ...
# \x1b is removing color formating and everything untill the first letter it finds
# the rest is a regexp; the \n are references: \1=title | \2=current ep | \3=all ep | \4=score |
# }}}

# Covers functions using ueberzug {{{
# https://github.com/seebye/ueberzug/blob/master/examples/fzfimg.sh
adl_covers() {
  # for a python way, check the homepage
  url=$(curl "https://graphql.anilist.co" \
    --silent -X POST -H 'content-type: application/json' -H 'accept: application/json' \
    --data "{\"query\":\"query (\$id: Int, \$search: String) {Media (id: \$id, search: \$search, type: ANIME) {id coverImage {large}}}\", \"variables\": {\"search\": \"$1\"}}")
  url=$(echo "$url" | sed -n 's/\\//g; s/.*"\(http.*\)".*/\1/p')
  wget --quiet "$url" -O "/tmp/$1.png"
}
UEBERZUG_FIFO="$(mktemp --dry-run --suffix "fzf-$$-ueberzug")"
declare -r -x UEBERZUG_FIFO
start_ueberzug() {
  mkfifo "${UEBERZUG_FIFO}"
  <"${UEBERZUG_FIFO}" \
      ueberzug layer --parser bash --silent &
  # prevent EOF
  3>"${UEBERZUG_FIFO}" \
      exec
}
draw_preview() {
  img=$(echo "${@}" | perl -pe "s/\x1b\[[0-9;]*m//g ; s/^.+?[^\s]\s+(.+?(?=\.\.))\.+\ +(\d+).[^\d]\ (\d+|\?)\s+(\d*[.]?\d+).+$/\1/g")
  [ ! -s "/tmp/$img.png" ] && adl_covers "$img"

  >"${UEBERZUG_FIFO}" declare -A -p cmd=( \
      [action]=add [identifier]="preview" \
      [x]="2" [y]="1" \
      [width]="$((COLUMNS-2))" [height]="$((LINES-3))" \
      [scaler]=fit_contain [scaling_position_x]=0.5 [scaling_position_y]=0.5 \
      [path]="/tmp/$img.png")
      # add [synchronously_draw]=True if you want to see each change
}
set_fzf_covers() {
  if [[ "$covers" == "1" ]]; then
    check_covers
    _fzf_prompt="Colored entries are Airing. Type to search. Press enter to select "
    # export is needed so it can work in fzf --preview
    export -f draw_preview
    export -f adl_covers
    fzf_select() {
      start_ueberzug
      # disabled multi-select with +m as the codebase changed. Still works but you get another prompt
      fzf --ansi --reverse --cycle +m --prompt "$_fzf_prompt" \
          --preview "draw_preview {}" --preview-window "left,20%"
      pkill ueberzug
      rm "${UEBERZUG_FIFO}"
    }
  else
    fzf_select() {
      fzf --ansi --reverse --cycle +m --prompt "$_fzf_prompt" \
          --preview "echo 'adl has now cover support. Try \$adl -c.'" --preview-window "down,5%"
    }
  fi
}
# }}}

select_function() { #{{{
  # Retrieve title and nr. Parse file only once
  if [[ -z "$1" ]]; then
    if [[ -z "$use_frece" ]]; then
      entry="$(echo "$tlist" | fzf_select | process_list)"
      present=""
    else
      check_frece
      entry="$(echo "$tlist" | process_list)"
      present=""

      echo "$entry" | cut -d'|' -f1 > "$ENTRIES_FILE"
      # Create database
      if [ ! -f "$DB_FILE" ]; then
          frece init "$DB_FILE" "$ENTRIES_FILE"
      else
          frece update "$DB_FILE" "$ENTRIES_FILE" --purge-old
      fi

      cp "$DB_FILE" "$FZF_FILE"
      readarray -t lines <<< "$(frece print "$DB_FILE")"
      for line in "${lines[@]}"; do
        chosen="$(echo "$tlist" | grep "$line" | sed 's/\//\\\//g; s/|/\\|/g; s/\&/\\&/g')"
        # for every in copied database replace that line with the trackma -a "$account" style line
        sed -i "/$line/{s/$line/$chosen/g}" "$FZF_FILE"
      done

      line_number=1
      # cleanup this file
      [[ -e "$ENTRIES_FILE" ]] && rm "$ENTRIES_FILE"
      choice="$(frece print "$FZF_FILE" | \
        while IFS= read -r line ; do
          [[ $line_number -lt 10 ]] && echo "$line" | sed -e "s/\(.\{9\}\)//; s/^/${line_number}\ \  /; s/^/|   /" || \
          echo "$line" | sed -e "s/\(.\{9\}\)//; s/^/${line_number}\  /; s/^/|   /"
          ((line_number++)); done | fzf_select)"
      # deal with ctrlc at fzf for frece; otherwise will print "Entry not found in database"
      [[ "$choice" == "" ]] && print_noselect && return 0
      echo "$choice" | process_list | \
        while IFS= read -r line ; do
          # reuse this file
          echo "$line" >> "$ENTRIES_FILE"
          frece increment "$DB_FILE" "$(echo "$line" | cut -d'|' -f1)"
        done
    fi
  else
    # retrieved custom show from adl input
    entry="$1"
    present="0"
  fi

  if [[ -z "$use_frece" ]]; then
    readarray -t lines <<< "$entry"
    # test for ctrlc at fzf select screen
    [[ "$lines" == "" ]] && print_noselect && return 0
    for line in "${lines[@]}"; do
      watch "$line" "$present"
      echo
    done
  else
    # for frece we get lines from a file
    readarray -t lines <<< "$(cat "$ENTRIES_FILE")"
    # testing for empty above instead to avoid an error
    for line in "${lines[@]}"; do
      chosen=$(echo "$entry" | grep "$line")
      watch "$chosen" "$present"
      echo
    done
  fi

} #}}}

animedl() { #{{{
  # initialise trap to call trap_ctrlc function when signal 2 (SIGINT) is received
  trap "trap_ctrlc" 2
  color_print "You can press Ctrl+C to cancel watching. That episode won't be counted."
  # echo "$title $3 $4"
  local out=""

  if [ "$local" == "0" ]; then
    # I can't seem to get anime dl to work unless I use a function like this
    choice_arg()   { [[ -z "$yes" ]] && echo "" || echo "-c 1" ;}
    player_arg="$1"
    down_arg()     { [[ "$download" == "0" ]] && echo "--play $player_arg"   || echo "" ;}
    provider_arg() { [[ "$provider" != ""  ]] && echo "--provider $provider" || echo "" ;}
    if [[ "$4" != "" ]]; then
      { out=$(anime dl $(down_arg) "$2" --episodes "$3":"$4" $(choice_arg) $(provider_arg) | tee >(cat - >&5)); } 5>&1
      animedl_args="$3 $4" # remember episode numbers for provider retry
    else
      if [[ "$3" != "" ]]; then
        { out=$(anime dl $(down_arg) "$2" --episodes "$3" $(choice_arg) $(provider_arg) | tee >(cat - >&5)); } 5>&1
        animedl_args="$3"
      else
        { out=$(anime dl $(down_arg) "$2" $(choice_arg) $(provider_arg) | tee >(cat - >&5)); } 5>&1
        animedl_args=""
      fi
    fi
  else
    # instead of streaming, play from local media
    # this obviously requires identical folder names to ones on anilist
    _find_files() {
      find "$1" -maxdepth 1 \
        -type l,f \( -name "*.srt" -o -name "*.ass" \) -prune \
        -o -type l,f -name "*" -print | sort
    }
    _proc_files() {
      local _c="$2"
      # for better searching have 0X instead of X
      if [ "$_c"  != "" ]; then
         [ "$_c" -lt 10 ] && _c="0$_c"
      fi
      _find_files "$1" | \
      perl -ne "/(?!.*\/)(?<!S|H|H\.|x|x\.|19|20|2)($_c+)(?!([0-9]0p)|([0-9]{2}))(?!([^a-z]+)(bits|bit))(?![^\(]*\)|[^\[]*\]|[^\{]*\})/i && print" \
      2> /dev/null | \
      fzf -e --ansi --keep-right --cycle --preview "echo 'Episode number to select: $_c'" --preview-window "up,5%"
      # Explination {{{
      # $1 is the path; maxdepth to not go into OP/ED/Scans etc
      # prune any subtitle files from results
      # print all files found into perl, include symlinks
      # use perl to find EP only file, by not matching other things:
      # - (?!.*\/)                   match after last slash
      # - (?<!S|H|H.\|x|x\.|19|20|2) ignore S0X only, H264, H.264, x264, x.264 and years (ex 201x or 2020)
      # - (?!([0-9]0p)|([0-9]{2}))   ignore resolution size such as 1080p (ex ep 10), also years (ex 2020)
      # - (?!([^a-z]+)(bits|bit))    ignore 10*bit(s) (ex ep 10)
      # - lastly exclude anything inside () [] {}
      # - case insensitive regex for X264
      # - warning 'Variable length lookbehind is experimental in regex' thus 2> /dev/null
      # }}}
    }
    if [[ "$4" != "" ]]; then
      list=""; local out="";
      # check for multi-select or not
      if [[ "$ans_episode" == "m" ]]; then
        # get all anime episodes in one variable using fzf multi select
        # mbuffer to show previous episodes
        list="$(_find_files "$animedir/$2" | sed -ne "/$(($3-$mbuffer))/,$ p" | \
          fzf -m --reverse --ansi --keep-right --cycle --prompt 'Multi select with tab/shift+tab. Order matters. Enter to confirm: '\
          --preview "echo 'Current episode to watch: $3. Change mbuffer to display previous episodes.'" --preview-window "up,5%")"
      else
        # if we know episode range, create list line by line
        for i in $(seq "$3" "$4"); do
          list+="$(_proc_files "$animedir/$2/" "$i")\n"
        done
      fi
      # test if ctrl-c at fzf (if list empty)
      [[ "$list" != *"$2"* ]] && print_noselect && return 0
      # get number of episodes selected, used for ans_continue later
      # for multi option, this is needed
      animedl_args="$3 $(($3 - 1 + $(wc -l <<< "$list") ))"
      # for each line open mpv
      # read -d changes the delimiter character used to mark the end of an input line; needed for multi fzf
      while IFS= read -r -d$'\n' line; do
        if [ "$ctrlc" = 0 ]; then
          { out+=$($player "$line" | tee >(cat - >&5)); } 5>&1
        else return 1; fi
      done <<< $(echo -e "$list")
    else
      if [[ "$3" != "" ]]; then
        { out=$($player "$(_proc_files "$animedir/$2/" "$3")" | tee >(cat - >&5)); } 5>&1
        animedl_args="$3"
      else
        { out=$($player "$(_proc_files "$animedir/$2/" "")" | tee >(cat - >&5)); } 5>&1
        animedl_args=""
      fi
    fi
  fi

  # Initialize watched counter
  # set -x # errors when loading file > still counted episode
  case $player in
    "vlc")
      watched=$((watched + $(echo "$out" | grep -c 'Command Line Interface initialized') )) ;;
    "mpv"|"mplayer")
      watched=$((watched + $(echo "$out" | grep -c -E "Exiting... (\(Quit\)|\(End of file\))") ))
      # consider possible errors
      # err=$(echo "$out" | grep -c -E 'Errors when loading file|ERROR')
      # [[ "$err" != "0" ]] && watched=$((watched - err))
      ;;
    *)
      watched=$((watched + 1)) ;;
  esac
  # check if anime downloader threw an error
  if echo "$out" | grep -q "Aborted!"; then
    ctrlc="1"
  fi
  if echo "$out" | grep -q "No such file or directory"; then
    ferr="1"
  fi
  # it seems like this decrease is not needed anymore
  # [[ "$ctrlc" == "1" ]] && watched=$((watched - 1)) # if Ctrl-C was caught one extra episode was counted
  [[ "$watched" -lt 0 ]] && watched=0 ;
} #}}}

watch() { #{{{
  title="$(echo "$1" | cut -d'|' -f1)"
  nr="$(($(echo "$1" | cut -d'|' -f2) + 1))" #dat spacing tho
   last="$(echo "$1" | cut -d'|' -f3)"
  score="$(echo "$1" | cut -d'|' -f4)"
  [[ "$last" == "?" ]] && last=$((nr + 12))
  sent=""

  check_exceptions

  echo "$title > $((nr-1)) / $last"

  if [ -z "$show_episode" ]; then # if -n was used skip this, -r will be chosen
    color_print "Enter lowercase or uppercase to issue command:
      N - Next episode (default, press <ENTER>)
      M - Multi select of episodes. You see available filenames
    0-9 - Plus n episodes relative to last seen (type number)
      L - from current to Last known
      A - All available, from episode 1
      I - custom Interval (range) of episodes
      R - Rewatch/redownload current episode in list
      C - Custom episode
      U - Update entry chosen instead of streaming
      S - Skip. Choose another show."
    color_prompt "Your choice? [N/m/0-9/l/a/i/r/c/u/s]: "
    if [[ -z "$yes" ]]; then read ans_episode
    else ans_episode="n" && print_noconfirm
    fi
  else ans_episode="r"
  fi
  no_update=0
  case $ans_episode in
    ""|"n"|"N")
      watching_prompt "$title" "episode" "#$nr"
      animedl "$player" "$title" "$nr" ;;
    "l"|"L")
      if [[ "$last" != "?" ]]; then
        watching_prompt "$title" "starting with episode" "#$nr"
        animedl "$player" "$title" "$nr" "$last"
      else
        color_print "The last episode number is unknown."
        color_prompt "How many episodes after currnet you want to watch? : "
        if [[ -z "$yes" ]]; then read -r ans_nr
        else ans_nr="" ; print_noconfirm
        fi
        [[ $ans_nr != "" ]] && last=$((nr + ans_nr)) || last=$((nr + 5))
        watching_prompt "$title" "episodes" "#$nr to #$last"
        animedl "$player" "$title" "$nr" "$last"
      fi ;;
    "a"|"A")
      watching_prompt "$title" "starting with episode" "#1"
      animedl "$player" "$title" ;;
    "i"|"I")
      color_prompt "Starting episode of episodes range: "
      read -r interval_start
      color_prompt "Last episode of episodes range: "
      read -r interval_stop
      watching_prompt "$title" "episodes" "#$interval_start to #$interval_stop"
      animedl "$player" "$title" "$interval_start" "$interval_stop" ;;
    "m"|"M")
      ans_episode="m"
      watching_prompt "$title" "starting with episode" "#$nr"
      animedl "$player" "$title" "$nr" "$((nr + 1))" ;;
    *[0-9]*) # If user gives number, assume P option from before
      # check if answer is not number or is 0
      if [[ ! $ans_episode =~ ^[0-9]+$ ]] || [[ "$ans_episode" == "0" ]] ; then
        ans_episode=1
      fi
      watching_prompt "$title" "episodes" "#$nr to #$((ans_episode + nr - 1))"
      animedl "$player" "$title" "$nr" "$((ans_episode + nr - 1))" ;;
    "r"|"R")
      no_update=1
      nr=$((nr - 1))
      watching_prompt "$title" "episode" "#$nr"
      animedl "$player" "$title" "$nr" ;;
    "c"|"C")
      no_update=1
      color_prompt "Enter custom number: "
      read -r nr
      watching_prompt "$title" "episode" "#$nr"
      animedl "$player" "$title" "$nr" ;;
    "u"|"U")
      color_print "\nSkipping watching episodes. Modifing entry."
      color_prompt "Update episode number or update score [E/s]: "

      read -r ans_modify
      case $ans_modify in
        ""|"e"|"E")
          color_print "Current episode for $title is $((nr - 1))."
          color_prompt "Enter updated episode number: "
          read -r custom
          [[ $custom != "" ]] && trackma -a "$account" update "$title" "$custom" || color_print "Skipping updating..." ;;
        "s"|"S")
          color_print "Current score for $title is $score."
          color_prompt "Enter udated score: "
          read -r custom
          [[ $custom != "" ]] && trackma -a "$account" score "$title" "$custom" || color_print "Skipping scoring..." ;;
      esac
      if [[ $custom != "" ]];  then
        trackma -a "$account" send
        sent="1"
      fi
      return 0 ;;
    "s"|"S")
      color_print "Skipping current entry."
      return 0 ;;
    *)
      color_print "Option not available."
      return 0 ;;
  esac

  while true; do
    if [[ "$watched" == "0" && "$ctrlc" == "0" && "$download" == "0" && "$local" == "0" ]]; then
      color_print "\n$player didn't start, the anime wasn't found, or the episode wasn't found..."
      color_prompt "Try another provider? [N / provider name]: "
      read -r provider_ans
      case $provider_ans in
        ""|"n"|"N")
          color_print "Skipping different provider retry..."
          provider_ans="n" ;;
        *)
          provider="$provider_ans"
          color_print "Now trying $provider. $0 will remember this.\n"
          reset_vars
          animedl "$player" "$title" $(echo "$animedl_args")
          ;;
      esac
    fi

  # Continue watching
    if [[ -z "$yes" && "$ctrlc" == "0" && "$provider_ans" != "n" && "$ferr" != "1" && "$((watched+nr-1))" != "$last" ]]; then
      [[ "$download" == "0" ]] && var="watch" || var="download";
      color_prompt "\nWant to further $var the anime? Enter number for ep. count, [N/0-9]: "
      read -r ans_continue
    else ans_continue="n"
    fi
    case $ans_continue in
      ""|"n"|"N")
        color_print "Proceeding..."
        break ;;
      *[0-9]*) # user wants to continue watching/downloading
        reset_vars
        # animedl_args will be either '[0-9] [0-9]' or '[0-9]'; get last number
        animedl_last=$(echo "$animedl_args" | awk '{print $NF}')
        # last was done, so continue from last+1
        if [[ $ans_continue -gt 1 ]]; then
          watching_prompt "$title" "episodes" "#$((animedl_last + 1)) to #$((animedl_last + ans_continue))"
        else
          watching_prompt "$title" "episode" "#$((animedl_last + 1))"
        fi
        animedl "$player" "$title" $((animedl_last + 1)) $((animedl_last + ans_continue))
    esac
  done

  #only ask if anime is in list, only if streaming, only if there is something to even update
  if [[ -z "$2" && "$download" == "0" && "$watched" -gt 0 && "$no_update" != "1" ]]; then
    echo -en "\033[0;34mIncrease nr in anime list by \033[0m$watched\033[0;34m? Yes, no, or custom number [Y/n/0-9]: \033[0m"
    if [[ -z "$yes" ]]; then read ans_update
    else ans_update="" && print_noconfirm
    fi


    case $ans_update in
      ""|"y"|"Y")
        [[ $no_update == 1 ]] && color_print "No need to update..." && return 0; #exit if option r/R was used before
        [[ "$watched" -gt 1  ]] && nr=$((watched + nr - 1));
        if [[ $last == "?" ]]; then
           trackma -a "$account" update "$title" "$nr"
        else
          [[ $nr -le $last ]] && trackma -a "$account" update "$title" "$nr" || trackma -a "$account" update "$title" "$last"
        fi
        if [[ $score == 0 ]] && [[ $nr -ge $last ]] ; then
          color_prompt "\nAnime will be set to completed. Also rate the anime? Type score: "
          read -r ans_score
          [[ $ans_score != "" ]] && trackma -a "$account" score "$title" "$ans_score" || color_print "Skipping scoring...";
        fi
        trackma -a "$account" send
        sent="1"
        ;;
      "n"|"N")
        sent=""
        color_print "Skipping..."
        ;;
      *[0-9]*)
        trackma -a "$account" update "$title" "$((nr + ans_update - 1))"
        trackma -a "$account" send
        sent="1"
        ;;
      *)
        color_print "Option not available."
        ;;
    esac
    check_exceptions
  fi
  watched=0
  watch_another
} #end of watch() }}}

show_function() { #{{{
  if echo "$tlist" | grep -q "$1" ;then
    color_print "Anime found in list. Proceeding.\n"
    select_function "$(echo "$tlist" | grep "$1" | process_list)"
  else
    color_prompt "Anime not found in list. Want to add it? [y/N]: "
    if [[ -z "$yes" ]]; then read ans_add
    else ans_add="" && print_noconfirm
    fi
    echo
    case $ans_add in
      "y"|"Y")
        trackma -a "$account" add "$1"
        trackma -a "$account" send
        color_print "\nRetrieving updated anime list...\n"
        get_list
        select_function ;; #anime is in list
      ""|"n"|"N")
        if [[ -n $2 ]]; then
          select_function "$1|$2|12|0" #episode nr was specified
        else
          color_print "Episode nr not specified. adl will proceed with a few guesses. \
          \nNext time add the anime to list or run: \"\$adl -s 'TITLE' -n 'EPISODE'\" \
          \nEpisode nr can still be specified later using 'Custom' option.\n"
          select_function "$1|$2|12|0" #episode nr was specified
        fi ;;
    esac
  fi
} #}}}

watch_another() { #{{{
  reset_vars
  if [[ -z "$yes" ]]; then
    local _state=""
    [[ "$download" == "0" ]] && _state="watch" || _state="download"
    color_prompt  "\nWant to $_state another anime? [Y/n] \
    \nType list query instead to change list and assume yes: "
    read -r ans_another
  else ans_another="n"
  fi
  # set -x
  case $ans_another in
    "completed"|"rewatching"|"paused"|"dropped"|"plantowatch"|"watching")
      query="$ans_another"
      local _msg="Retrieving updated $query anime list...\n"
      color_print "$_msg" && get_list && select_function
    ;;
    ""|"y"|"Y")
      local _msg="Retrieving updated $query anime list...\n"
      color_print "$_msg" && get_list && select_function
    ;;
    "n"|"N")
      color_print "Skipping watching another..." ;;
      # return 0 ;;
    *)
      print_queries ;;
  esac
} #}}}

updater() { #{{{
  DIR=$(cd "$(dirname "$0")" || exit ; pwd)
  FILE=$(basename "$0")
  MESSAGE="WARNING: $0 will now overwrite itself at the path: $DIR/$FILE. Proceed? [y/N]: "
  printf "\033[0;31m%s\033[0m" "$MESSAGE" #red warning
  # integration with -y option crossed my mind but it is unwise
  read -r updater_ans
  case $updater_ans in
    "y"|"Y")
      # color_prompt "\nadl can be updated from master or develop. Which one do you choose? [M/d]: "
      # read -r source_ans
      # case $source_ans in
      #   ""|"M"|"m")
      #     source="master"
      #     wget -q --show-progress "https://raw.githubusercontent.com/RaitaroH/adl/master/adl" -O "$DIR/$FILE" ;;
      #   "d"|"D")
      #     source="develop"
      #     wget -q --show-progress "https://raw.githubusercontent.com/RaitaroH/adl/develop/adl" -O "$DIR/$FILE" ;;
      #   *)
      #     color_print "Not an actual option. Exiting..."
      #     exit 1 ;;
      # esac
      wget -q --show-progress "https://raw.githubusercontent.com/RaitaroH/adl/master/adl" -O "$DIR/$FILE"
      color_print "\n✓ Update from master is complete." ;;
    ""|"n"|"N")
      color_print "Update aborted." ;;
    *)
      color_print "Not an actual option. Exiting..." ;;
  esac
} #}}}

arguments() { #{{{
  # check if option is interpreted as argument for previous option; match getopt error format
  # \ in printf because $2 was expanded into an argument for printf
  if printf "%s" "$2" | grep -q "-"; then
    echo "$0: option requires an argument -- '$1'"
    print_options
    exit 1
  else eval "$3='$(xargs <<< "$2")'"
  fi
} #}}}

if ! params="$(getopt -o vhup:i:s:n:a:q:yrdl:fc \
                      -l version,help,update,player:,provider:,show:,number:,account:,query:,no-confirm,retrieve,download,local:,frece,covers \
                      --name "$0" -- "$@")"; then print_options && exit 1; fi
eval set -- "$params"

while true; do
  opt="$1"
  case "$opt" in
    -v|--version)    print_version  ;  exit 0 ;;
    -h|--help)       print_help     ;  exit 0 ;;
    -u|--update)     updater        ;  exit 0 ;;
    -p|--player)     arguments "$opt" "$2" player ;;
    -i|--provider)   arguments "$opt" "$2" provider ;;
    -s|--show)       arguments "$opt" "$2" show_title ;;
    -n|--number)     arguments "$opt" "$2" show_episode ;;
    -a|--account)    arguments "$opt" "$2" account ;;
    -q|--query)      arguments "$opt" "$2" query ;;
    -y|--no-confirm) yes="1"       ;; # Assume default; vlc breaks if 1 is piped into anime-dl
    -r|--retrieve)   retrieve="1"  ;; # Run trackma retrieve
    -d|--download)   download="1"  ;; # Download instead of streaming
    -l|--local)      arguments "$opt" "$2" animedir; local=1 ;; # Use local media instead of streaming
    -f|--frece)      use_frece="1" ;;
    -c|--covers)     covers="1" ;;
    --) shift; break ;; # exit loop
  esac
  shift
done

check_player
set_fzf_covers
get_list
if [[ -z "$show_title" ]]; then select_function
else show_function "$show_title" "$show_episode"
fi

# Cleanup
[[ -e "$ENTRIES_FILE" ]] && rm "$ENTRIES_FILE"
[[ -e "$FZF_FILE" ]] && rm "$FZF_FILE"
color_print "\nThank you for using adl ✨! \nExiting."
