#!/bin/bash
# version: 1.6
# Wrapper for anime-donwloader. Allows using watchlist given by trackma for a better anime watching cli experience.

tlist=$(trackma list | awk -F'  ' 'NR>1 {split($4,t,".");gsub(" ", "", $5);split($5,n,"/");print t[1]"|"n[1]"|"n[2]}' |\
  head -n -2 | sed 's/\x1b\[[0-9;]*m//g')
# awk explination ...
# delimeter set to 2x space
# NR>1 ignore first line
# $4 is the title plus dots ... split allows to remove the dots, sets new result to var t
# $5 is Current / All episodes split allows to get the current episode number
# gsub thingy is to remove beggining space " 2" from one digit numbers
# finally print t[1] = title and n[1] current episode number: result is like so:    Animu|x
# head is used here to remove the last 2 lines which are also not needed
# that sed at the end is to strip color from the output
# finally for real now, output that stuff to a file

# Retrieve title and nr. cat file only once
entry="$(echo $tlist | fzf --height=15% --tac)"
title="$(echo $entry | cut -d'|' -f1)"
nr="$(($(echo $entry | cut -d'|' -f2) + 1))" #dat spacing tho
  last="$(echo $entry | cut -d'|' -f3)"

color_echo() { echo "Now watching \033[0;34m$1\033[0m, $2 \033[0;34m$3 \033[0m" ;}
color_prompt() { echo "\033[0;36m$@ \033[0m" ;}
# for better readability $title and $nr will be blue
# You can find other colors here: https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux

color_prompt "Next episode, starting from next to last aired, or all available? Alternatively skip and update entry. [N/l/a/s]"
read ans
case $ans in
  ""|"n"|"N")
    color_echo $title "episode" "#$nr"
    anime dl --play vlc $title --episodes $nr 2> /dev/null ;;
  "l"|"L")
    color_echo $title "starting with episode" "#$nr"
    anime dl --play vlc $title --episodes $nr:$last 2> /dev/null ;;
  "a"|"A")
    color_echo $title "starting with episode" "#1"
    anime dl --play vlc $title 2> /dev/null ;;
  "s"|"S")
    color_prompt "Skipping watching episodes."
    color_prompt "Enter custom number:"
    read custom
    trackma update $title $custom
    trackma send
    exit 1 ;;
esac

color_prompt "If vlc didn't start, the anime wasn't found"
color_prompt "Increase nr in anime list? Yes, no, or custom number [Y/n/c]"
read ans
case $ans in
  ""|"y"|"Y")
    trackma update $title $nr
    trackma send ;;
  "n"|"N")
    color_prompt "Exiting." ;;
  "c"|"C")
    color_prompt "Enter custom number:"
    read custom
    trackma update $title $custom
    trackma send ;;
esac
